### ISSUE TITLE
Precompilation issue on Windows

### ISSUE THREAD

**Issue by Felix-Gauthier** [etpinard/dash-textarea-autocomplete#7]
When git cloning to windows : 

``` 
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'src/DashTextareaAutocomplete.jl'
  'src/dashtextareaautocomplete.jl'
```

Leaving precompilation of the package broken.

**Comment by etpinard** [comment]
Thanks for the headsup!

This is essentially a bug in https://github.com/plotly/dash-component-boilerplate

**Comment by etpinard** [comment]
Should be fixed now in `v1.0.1` https://github.com/JuliaRegistries/General/pull/34281

**Comment by Felix-Gauthier** [comment]
Awesome thanks! I'll give it a go and report 👍

**Comment by Felix-Gauthier** [comment]
Issue resolved, closing.
